#empty tuple
# t=()
# t=(1,2,3)
# print(t)
# t=(1,"raju",2,"ram")
# print(t)
# t=(1,(2,3,4,5),["ram","shayam","geeta"])
# print(t)
# t=("satish")
# print(type(t))
# t=(1,)
# print(type(t))
# t="satish",
# print(type(t))
# t=('satish','murali','naveen','shrinu')
# print(t[1])
# print(t[-1])
# t=('ABC',('satish','naveen','shrinu'))
# print(t[1][2])
# t=(1,2,3,4,5,6,{12,14,89})
# print(t[1:4])
# print(t[:-2])
# print(t[:])
# t=(1,2,3,4,['x','y','z'])
# t[2]='x'
# print(t)
# t[4][1]='satish'
# print(t)
# t=('a','b','c','d')
# t2=('e','f','g','h')
# print(t+t2)
# t=('a','b','c')*4
# print(t)
# del t
# print(t)
# t=(1,1,2,3,4,5,6,8,1,0)
# print(t.count(1))
# print(t.index(0))
# print(1 in t)
# print(len(t))
# new_t=sorted(t)
# print(new_t)
# print(max(t))
# print(min(t))
# #t=('ram','shyam','raju','seeta')
# print(max(t))
# print(sum(t))
price=(120,80,150,200,90)
## total money
total=sum(price)
print(total)
## highest and lowes price of stock
hprice=max(price)
print("Maximum price of stock is",hprice)
lprice=min(price)
print("Minimum price of stock is",lprice)
price1=(110,)
print(price+price1)
